/* 
 * MIT License
 *
 * Copyright (c) 2020 Ghosty
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:

 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 * All MIDI status bytes with their corresponding name
 */
 
#define CHAN_1_NOTE_OFF 0x80
#define CHAN_2_NOTE_OFF 0x81
#define CHAN_3_NOTE_OFF 0x82
#define CHAN_4_NOTE_OFF 0x83
#define CHAN_5_NOTE_OFF 0x84
#define CHAN_6_NOTE_OFF 0x85
#define CHAN_7_NOTE_OFF 0x86
#define CHAN_8_NOTE_OFF 0x87
#define CHAN_9_NOTE_OFF 0x88
#define CHAN_10_NOTE_OFF 0x89
#define CHAN_11_NOTE_OFF 0x8A
#define CHAN_12_NOTE_OFF 0x8B
#define CHAN_13_NOTE_OFF 0x8C
#define CHAN_14_NOTE_OFF 0x8D
#define CHAN_15_NOTE_OFF 0x8E
#define CHAN_16_NOTE_OFF 0x8F
#define CHAN_1_NOTE_ON 0x90
#define CHAN_2_NOTE_ON 0x91
#define CHAN_3_NOTE_ON 0x92
#define CHAN_4_NOTE_ON 0x93
#define CHAN_5_NOTE_ON 0x94
#define CHAN_6_NOTE_ON 0x95
#define CHAN_7_NOTE_ON 0x96
#define CHAN_8_NOTE_ON 0x97
#define CHAN_9_NOTE_ON 0x98
#define CHAN_10_NOTE_ON 0x99
#define CHAN_11_NOTE_ON 0x9A
#define CHAN_12_NOTE_ON 0x9B
#define CHAN_13_NOTE_ON 0x9C
#define CHAN_14_NOTE_ON 0x9D
#define CHAN_15_NOTE_ON 0x9E
#define CHAN_16_NOTE_ON 0x9F
#define CHAN_1_POLYPHONIC_AFTERTOUCH 0xA0
#define CHAN_2_POLYPHONIC_AFTERTOUCH 0xA1
#define CHAN_3_POLYPHONIC_AFTERTOUCH 0xA2
#define CHAN_4_POLYPHONIC_AFTERTOUCH 0xA3
#define CHAN_5_POLYPHONIC_AFTERTOUCH 0xA4
#define CHAN_6_POLYPHONIC_AFTERTOUCH 0xA5
#define CHAN_7_POLYPHONIC_AFTERTOUCH 0xA6
#define CHAN_8_POLYPHONIC_AFTERTOUCH 0xA7
#define CHAN_9_POLYPHONIC_AFTERTOUCH 0xA8
#define CHAN_10_POLYPHONIC_AFTERTOUCH 0xA9
#define CHAN_11_POLYPHONIC_AFTERTOUCH 0xAA
#define CHAN_12_POLYPHONIC_AFTERTOUCH 0xAB
#define CHAN_13_POLYPHONIC_AFTERTOUCH 0xAC
#define CHAN_14_POLYPHONIC_AFTERTOUCH 0xAD
#define CHAN_15_POLYPHONIC_AFTERTOUCH 0xAE
#define CHAN_16_POLYPHONIC_AFTERTOUCH 0xAF
#define CHAN_1_CONTROL_MODE_CHANGE 0xB0
#define CHAN_2_CONTROL_MODE_CHANGE 0xB1
#define CHAN_3_CONTROL_MODE_CHANGE 0xB2
#define CHAN_4_CONTROL_MODE_CHANGE 0xB3
#define CHAN_5_CONTROL_MODE_CHANGE 0xB4
#define CHAN_6_CONTROL_MODE_CHANGE 0xB5
#define CHAN_7_CONTROL_MODE_CHANGE 0xB6
#define CHAN_8_CONTROL_MODE_CHANGE 0xB7
#define CHAN_9_CONTROL_MODE_CHANGE 0xB8
#define CHAN_10_CONTROL_MODE_CHANGE 0xB9
#define CHAN_11_CONTROL_MODE_CHANGE 0xBA
#define CHAN_12_CONTROL_MODE_CHANGE 0xBB
#define CHAN_13_CONTROL_MODE_CHANGE 0xBC
#define CHAN_14_CONTROL_MODE_CHANGE 0xBD
#define CHAN_15_CONTROL_MODE_CHANGE 0xBE
#define CHAN_16_CONTROL_MODE_CHANGE 0xBF
#define CHAN_1_PROGRAM_CHANGE 0xC0
#define CHAN_2_PROGRAM_CHANGE 0xC1
#define CHAN_3_PROGRAM_CHANGE 0xC2
#define CHAN_4_PROGRAM_CHANGE 0xC3
#define CHAN_5_PROGRAM_CHANGE 0xC4
#define CHAN_6_PROGRAM_CHANGE 0xC5
#define CHAN_7_PROGRAM_CHANGE 0xC6
#define CHAN_8_PROGRAM_CHANGE 0xC7
#define CHAN_9_PROGRAM_CHANGE 0xC8
#define CHAN_10_PROGRAM_CHANGE 0xC9
#define CHAN_11_PROGRAM_CHANGE 0xCA
#define CHAN_12_PROGRAM_CHANGE 0xCB
#define CHAN_13_PROGRAM_CHANGE 0xCC
#define CHAN_14_PROGRAM_CHANGE 0xCD
#define CHAN_15_PROGRAM_CHANGE 0xCE
#define CHAN_16_PROGRAM_CHANGE 0xCF
#define CHAN_1_CHANNEL_AFTERTOUCH 0xD0
#define CHAN_2_CHANNEL_AFTERTOUCH 0xD1
#define CHAN_3_CHANNEL_AFTERTOUCH 0xD2
#define CHAN_4_CHANNEL_AFTERTOUCH 0xD3
#define CHAN_5_CHANNEL_AFTERTOUCH 0xD4
#define CHAN_6_CHANNEL_AFTERTOUCH 0xD5
#define CHAN_7_CHANNEL_AFTERTOUCH 0xD6
#define CHAN_8_CHANNEL_AFTERTOUCH 0xD7
#define CHAN_9_CHANNEL_AFTERTOUCH 0xD8
#define CHAN_10_CHANNEL_AFTERTOUCH 0xD9
#define CHAN_11_CHANNEL_AFTERTOUCH 0xDA
#define CHAN_12_CHANNEL_AFTERTOUCH 0xDB
#define CHAN_13_CHANNEL_AFTERTOUCH 0xDC
#define CHAN_14_CHANNEL_AFTERTOUCH 0xDD
#define CHAN_15_CHANNEL_AFTERTOUCH 0xDE
#define CHAN_16_CHANNEL_AFTERTOUCH 0xDF
#define CHAN_1_PITCH_BEND_CHANGE 0xE0
#define CHAN_2_PITCH_BEND_CHANGE 0xE1
#define CHAN_3_PITCH_BEND_CHANGE 0xE2
#define CHAN_4_PITCH_BEND_CHANGE 0xE3
#define CHAN_5_PITCH_BEND_CHANGE 0xE4
#define CHAN_6_PITCH_BEND_CHANGE 0xE5
#define CHAN_7_PITCH_BEND_CHANGE 0xE6
#define CHAN_8_PITCH_BEND_CHANGE 0xE7
#define CHAN_9_PITCH_BEND_CHANGE 0xE8
#define CHAN_10_PITCH_BEND_CHANGE 0xE9
#define CHAN_11_PITCH_BEND_CHANGE 0xEA
#define CHAN_12_PITCH_BEND_CHANGE 0xEB
#define CHAN_13_PITCH_BEND_CHANGE 0xEC
#define CHAN_14_PITCH_BEND_CHANGE 0xED
#define CHAN_15_PITCH_BEND_CHANGE 0xEE
#define CHAN_16_PITCH_BEND_CHANGE 0xEF
#define SYSTEM_EXCLUSIVE 0xF0
#define MIDI_TIME_CODE_QTR_FRAME 0xF1
#define SONG_POSITION_POINTER 0xF2
#define SONG_SELECT 0xF3
#define UNDEFINED_RESERVED_1 0xF4
#define UNDEFINED_RESERVED_2 0xF5
#define TUNE_REQUEST 0xF6
#define END_OF_SYSEX 0xF7
#define TIMING_CLOCK 0xF8
#define UNDEFINED_RESERVED_3 0xF9
#define START 0xFA
#define CONTINUE 0xFB
#define STOP 0xFC
#define UNDEFINED_RESERVED_4 0xFD
#define ACTIVE_SENSING 0xFE
#define SYSTEM_RESET 0xFF
